spring:
  ai:
    deepseek:
      api-key: 1
      chat:
        options:
          model: deepseek-v4-flash
  application:
    name: learn-ai-code
server:
  port: 19999

logging:
  charset:
    console: UTF-8
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
    dev.langchain4j: DEBUG

langchain4j:
  open-ai:
    chat-model:
      log-requests: true
      log-responses: true

