spring:
  ai:
    deepseek:
      api-key: 1
      chat:
        options:
          model: deepseek-v4-flash
  application:
    name: spring-ai-samples
server:
  port: 19999

logging:
  charset:
    console: UTF-8
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
